### PR TITLE
[improvement]: more precise CheckMem function

### PR DESCRIPTION
**Pull request by broccoliSpicy**
#305

### CODE REVIEW

**Comment by Ngalstyan4** [comment]
Thanks for the PR @broccoliSpicy!
Scalar quantization is not yet supported for lantern_hnsw indexes So this is not urgent right now - the assumption of float arrays holds for all code paths rn.

Something like this will be added once we add quantization support

**Comment by broccoliSpicy** [comment]
Gotcha, I felt the codebase right now is not that fit for tackling existing issues so I did this PR.

is it cool if Lantern publish more issues or feature requests for the community to tackle?

**Comment by Ngalstyan4** [comment]
Please do! 
If possible, please also share your use cases and usage details whenever relevant for the issues you open.

**Comment by broccoliSpicy** [comment]
> Please do! If possible, please also share your use cases and usage details whenever relevant for the issues you open.

haha, sorry, I didn't state it clearly, I was trying to say if there are some feature requests, perhaps on Lantern's roadmap, that is suitable now for community contributors to work on

**Comment by Ngalstyan4** [comment]
If you are familiar with CPP allocator patterns, #147  might be a good one.
I just created another issue (#308) and we would love to see contributions on that as well.

**Comment by broccoliSpicy** [comment]
Thanks so much! 
I will definitely try.

**Pull request closed without merging**
